"""Onboard a league the store has never seen — the real entry point (P5/S4a).

`weekly_refresh` ADVANCES a league that is already in the store. `bench_cold_league` MEASURES the
other half and then deliberately throws it away. This is the half that keeps what it built.

**Why this module exists at all.** Until now nothing in this system had ever catalogued a league.
`build_db._catalog()` was the frozen 31-row corpus slate plus the one generated demo clone;
`load_league` refuses anything absent from it in as many words ("cataloging a brand-new league is
onboarding/P5, not the scoped reload"); and `bench_cold_league` rolls its load back specifically to
sidestep that gate, saying in its own docstring that "there is no single 'onboard a cold league'
entry point today. P5/S4 needs a real one; this composes the same steps in the same order
meanwhile." This is that entry point, and it composes nothing new.

**ONE CHAIN, NOT TWO.** `run_chain` below is the chain — fetch raw → resolve the scoring key from
THIS league's own settings → assert the substrate → join every week → band (season-gated) → spine →
schedule. `bench_cold_league` imports it and wraps each step in timing; this module wraps it in a
catalog write and a COMMIT. If the benchmark and the onboarder ever became two implementations of
the same sequence, the 8.4–10.3s P5/S0 measured would quietly stop describing what actually runs.
The seam is the `stage` argument: a factory returning a context manager per step. The benchmark
passes its `_Stage`; this module passes a printer.

**What it refuses, loudly.** A league outside V1's scope (not redraft), a league that is the first
on its scoring key (no `projection_consensus` — CODING_BIBLE §4: never silently mis-score), and a
league that belongs to another layer (the frozen corpus, the demo slate, the generated clone). It
does NOT refuse a league already in `connected_catalog` — that is a re-onboard, and it is required
to be a clean no-op.

    python -m application.data.serve.onboard_league --league <id> --season 2025 --dry-run
    python -m application.data.serve.onboard_league --league <id> --season 2025
"""

from __future__ import annotations

import argparse
import contextlib
from collections import defaultdict
from pathlib import Path

import polars as pl
import psycopg

from application.api import platforms
from application.api.db import database_url
from application.data import data_layer as dl
from application.data.corpus import compute_spine, harvest
from application.data.fetchers import sleeper
from application.data.serve import build_db
from application.data.transforms import (compute_manager_features, compute_ros_player_band,
                                         export_schedule, join_nfl_sleeper_weekly)
from application.data.transforms._keys import scoring_key_from_settings

_LINEAGE_MAX_HOPS = 10


# --- where a league may already live -------------------------------------------------------------

def _league_dirs(lid: str, season: int) -> dict[str, Path]:
    """Every directory a league-scoped run writes — the growth measurement, the teardown and the
    coldness check all read this, so they can't drift apart."""
    return {"raw_sleeper": dl._sleeper_league_dir(season, lid),
            "joined": dl._join_league_dir(lid),
            "derived": dl._league_dir(lid)}


def _assert_not_synthetic(lid: str) -> None:
    """A synthetic league is generated, not harvested (P5/S2d), so "cold" is not even the right
    question — there is nothing on Sleeper to fetch. Its on-disk directories would already trip the
    coldness check, but incidentally rather than for a stated reason; this says the reason."""
    if dl.is_synthetic(lid):
        raise SystemExit(
            f"league {lid} is SYNTHETIC — generated by build_demo_clone, not harvested from Sleeper. "
            "There is no cold load to run.")


def _warm_where(lid: str, season: int) -> tuple[list[str], list[str]]:
    """Where this league is already known, split into (RECORDED, ON DISK). P5/S4b.

    The split is the point, and it is what makes a crashed run recoverable. A registry or catalog row
    is a DECISION somebody recorded — this league belongs to the corpus, the demo slate, the clone,
    or somebody's connected set — and it means the league is not ours to onboard. On-disk league
    directories are a SIDE EFFECT of a run: they appear the moment a fetch starts and say nothing
    about whether anybody decided anything.

    Before S4b both were the same list, and that made the FIRST CRASH on a cold league permanent.
    `write_connected_league` runs AFTER `run_chain` (see `onboard`), so a crash anywhere in the ~10s
    chain leaves the three directories and no catalog row — and the next attempt found the
    directories, called the league warm and refused it for ever. The queue makes that reachable
    without a human: a job would land `rejected`, which is terminal by design, and the league could
    never be onboarded again by any route.
    """
    recorded, on_disk = [], []
    if dl.leagues_exists():
        if dl.read_leagues().filter(pl.col("league_id").cast(str) == lid).height:
            recorded.append("leagues.parquet")
    # EVERY catalog, not just the demo manifest. `_catalog()` is the union of three parquets, so a
    # coldness check that reads one of them is a coldness check that lies — and it lied by two.
    # `synthetic_catalog` was never checked: the `is_synthetic` short-circuit above only covers the
    # hardcoded SYNTHETIC_LEAGUE_IDS literal, so a second clone would have slipped straight through.
    # `connected_catalog` is new in S4a and is the one that will actually fill up.
    for label, exists, read in (("demo_manifest.parquet", dl.demo_manifest_exists, dl.read_demo_manifest),
                                ("synthetic_catalog.parquet", dl.synthetic_catalog_exists, dl.read_synthetic_catalog),
                                ("connected_catalog.parquet", dl.connected_catalog_exists, dl.read_connected_catalog)):
        if exists() and read().filter(pl.col("league_id").cast(str) == lid).height:
            recorded.append(label)
    # The frozen corpus manifest is not a served catalog, but a corpus league is emphatically not
    # cold — the spine ran on 269 of them — and its artifacts may have been swept while its manifest
    # row survived. Checking it here is what stops a "cold" run from being aimed at the corpus.
    if dl.corpus_manifest_exists():
        if dl.read_corpus_manifest().filter(pl.col("league_id").cast(str) == lid).height:
            recorded.append("corpus_manifest.parquet (the frozen 271-league corpus)")
    on_disk += [f"{k} ({p})" for k, p in _league_dirs(lid, season).items() if p.exists()]
    return recorded, on_disk


def assert_cold(lid: str, season: int) -> None:
    """A league is cold when the store has never seen it: absent from the registry, absent from
    EVERY catalog (all three served ones plus the frozen corpus manifest), and absent from all three
    on-disk league directories. Standing rule 1 in executable form — a fast total is a bug until
    this has passed, and the onboarder uses it as a precondition rather than a benchmark aid.

    It is also the "catalogued after" half of S4a's DoD: once `write_connected_league` has run, this
    function must REFUSE the same league. A coldness check that misses a catalog is a coldness check
    that lies, and until S4a it missed two.

    UNCHANGED BY S4b — it still refuses on either kind of warmth, which is what `bench_cold_league`
    needs from it (a benchmark aimed at a half-built league measures the gates, not the work). What
    S4b changed is `classify`, which now tells the two kinds apart.
    """
    _assert_not_synthetic(lid)
    recorded, on_disk = _warm_where(lid, season)
    if recorded or on_disk:
        raise SystemExit(
            f"league {lid} is NOT cold — present in: {', '.join(recorded + on_disk)}.\n"
            "Timing or onboarding a warm league measures the pipeline's per-step gates, not the "
            "work. Pick a league the store has never seen (do NOT delete an existing one's "
            "artifacts — that risks the frozen corpus and the demo slate).")


def classify(lid: str, season: int) -> str:
    """`cold`, `resume`, `reonboard`, or raise (it belongs to another layer).

    A flag would have been simpler and wrong. "Is this a re-onboard?" is a fact about the store, not
    an assertion the caller gets to make, and the outcomes are genuinely different: a cold league
    must do all the work, a re-onboard must be a clean no-op (S4a DoD clause 4), and a league that
    is part of the frozen corpus or the demo slate must never be reachable from here at all — that
    is how you overwrite a fixture the L2 ledger is derived from.

    `resume` IS NEW IN P5/S4b, and it is a correctness fix rather than a convenience. The catalog row
    is written AFTER the chain, so a crash inside those ~10 seconds leaves the on-disk directories
    and nothing else. Before this, the retry found those directories, called the league warm and
    refused — permanently, by every route, for a league that had merely been interrupted. Under the
    queue that refusal is a `rejected` job, which is terminal by design, so the first crash on a real
    user's league would have been the last time it could ever be connected.

    A league known ONLY on disk was not decided by anybody; it is the wreckage of a run. Resuming is
    safe because the chain's stages skip on artifact presence and `onboard` performs the catalog
    write and the load unconditionally, so a resumed run completes exactly the parts that did not
    finish. See `_warm_where` for why the two kinds of warmth are separated.
    """
    lid = str(lid)
    _assert_not_synthetic(lid)
    if dl.connected_catalog_exists():
        if dl.read_connected_catalog().filter(pl.col("league_id").cast(str) == lid).height:
            return "reonboard"
    recorded, on_disk = _warm_where(lid, season)
    if recorded:
        assert_cold(lid, season)    # raises, naming everything — one message, one home
    if on_disk:
        print(f"  RESUME: {lid} has artifacts on disk but no catalog row — a previous run did not "
              f"finish ({', '.join(on_disk)}). Completing it rather than refusing it.")
        return "resume"
    return "cold"


# --- the chain ------------------------------------------------------------------------------------

def _missing_raw_weeks(lid: str, season: int) -> list[int]:
    """Weeks Sleeper says are COMPLETE that this store has no matchups snapshot for. P5/S4b.

    The completeness question cannot be answered from disk alone, and that is why this costs one
    Sleeper call. A fetch interrupted at week 6 of 14 leaves weeks 1-6 — which on disk is
    indistinguishable from a live league that has only played six. The discriminator is how many
    weeks Sleeper considers finished, and it comes from `_determine_completed_weeks`, the SAME
    function `backfill` uses to decide what to write. Asking a different source would let the two
    drift, and the drift would present as a truncated league nobody noticed.

    Bounded by `_reg_end` because the join only ever runs to the end of the regular season: playoff
    weeks may legitimately be absent and are none of this check's business.
    """
    completed = sleeper._determine_completed_weeks(sleeper._get_nfl_state(), season)
    upto = min(completed, harvest._reg_end(lid, season))
    return [wk for wk in range(1, upto + 1)
            if not dl._sleeper_matchups_path(season, wk, lid).exists()]


@contextlib.contextmanager
def _print_stage(name: str):
    """The default stage observer: announce the step and nothing else. `bench_cold_league` passes a
    timing one instead, which is the only difference between measuring this chain and running it."""
    print(f"\n--- {name} ---")
    yield


def run_chain(lid: str, season: int, *, to_week: int | None, report: dict,
              stage=_print_stage, dossiers: bool = False) -> dict:
    """THE cold chain, in the real order, shared by the benchmark and the onboarder.

    Fills `report` in place and returns it. Every key it writes is consumed by
    `bench_cold_league.print_table` and by its `--json` output, so the names are a published
    interface — S0's numbers are keyed on them and S3 re-ran the benchmark to compare two machines.

    It does not touch Postgres and does not write a catalog row: this is the part that is identical
    whether you are measuring or committing.
    """
    # 1 · FETCH — the raw layer, exactly as the harvest pulls it (config → roster_positions →
    # lineup_slots → teams → every completed week's matchups + transactions). Gated on
    # `_raw_present` for the same reason harvest gates it: a re-run must not re-pull.
    with stage("fetch"):
        if harvest._raw_present(lid, season):
            # `_raw_present` is TRUE on config + teams + WEEK ONE — read its docstring. But
            # `_pull_raw` writes every completed week inside `sleeper.backfill`'s loop, so a run
            # that died at week 6 of 14 leaves the gate saying "present" over a TRUNCATED season.
            # The join below then joins only the weeks whose files exist, and the league goes on to
            # get a spine, a schedule, a catalog row, a Postgres load and `state=ready` — on half a
            # season. That is the P5 risk register's exact words, "never a half-built league that
            # looks complete", and the queue is what makes it reachable: it removes the human who
            # used to read this output. So verify the gate instead of trusting it, and REPAIR
            # rather than refuse — completing an interrupted fetch is what a retry is for.
            missing = _missing_raw_weeks(lid, season)
            if not missing:
                print("  raw already present and COMPLETE — skipped (this is the GATE, not the work)")
                report["fetch"] = "skipped (raw complete)"
            else:
                print(f"  raw is INCOMPLETE — no matchups for week(s) {missing}; a previous fetch "
                      f"was interrupted. Re-pulling.")
                harvest._pull_raw(lid, season)
                still = _missing_raw_weeks(lid, season)
                if still:
                    raise SystemExit(
                        f"league {lid} ({season}) is still missing matchups for week(s) {still} "
                        f"after a re-pull.\n"
                        "  Sleeper reports those weeks complete but will not serve them, so any "
                        "league built now would be a TRUNCATED season presented as a whole one.\n"
                        "  Refusing rather than building it: this is the failure that looks like "
                        "success.")
                report["fetch"] = f"RE-PULLED (was truncated, missing {missing})"
        else:
            harvest._pull_raw(lid, season)

    # The scoring key comes from THIS league's own settings. weekly_refresh._resolve_scoring_key
    # used to fall back to the is_mine league's key for anything absent from the catalog, which
    # would silently score a stranger's league on the owner's profile — never let a cold league
    # take that path. (S4a fixed that fallback; this call is what it was fixed to.)
    scoring_key = scoring_key_from_settings(dl.read_scoring_settings(season, league_id=lid))
    report["scoring_key"] = scoring_key
    substrate = dl._projection_consensus_path(season, scoring_key)
    report["substrate_present"] = substrate.exists()
    print(f"\nscoring_key = {scoring_key}   substrate present: {report['substrate_present']}")
    if not report["substrate_present"]:
        raise SystemExit(
            f"no {season} projection_consensus for scoring_key {scoring_key} ({substrate}).\n"
            "This league is the first on its key — build the substrate first "
            "(bench_cold_league --substrate). Onboarding it anyway would score it against another "
            "league's profile, which CODING_BIBLE §4 forbids: never silently mis-score.")

    reg_end = harvest._reg_end(lid, season)
    target = min(reg_end, to_week) if to_week else reg_end
    report["reg_end"], report["target_week"] = reg_end, target
    print(f"regular season ends wk{reg_end}; joining + computing through wk{target}")

    # 2 · JOIN — one week at a time, the authoritative player×week table. Starts after the
    # deepest week already joined, exactly like weekly_refresh, so a re-run is a no-op.
    with stage("join"):
        jp = dl._join_season_path(season, lid)
        done = int(pl.read_parquet(jp, columns=["week"])["week"].max()) if jp.exists() else 0
        joined = 0
        for wk in range(done + 1, target + 1):
            if dl._sleeper_matchups_path(season, wk, lid).exists():
                join_nfl_sleeper_weekly.run(season, wk, league_id=lid)
                joined += 1
        report["weeks_joined"] = joined
        report["weeks_already_joined"] = done

    # 2b · THE ZERO-WEEK REFUSAL — a league that has played nothing cannot be built (P5/S4d).
    #
    # This is where Will's live link test died, and the failure was the ugliest kind: the join
    # writes NO FILE when it joins no weeks, and `compute_production_vor` reads that parquet with
    # no existence guard, so the chain raised a bare `FileNotFoundError` carrying an internal
    # filesystem path — which the connect banner then rendered to the user verbatim.
    #
    # Three of the five spine reads already carry well-worded diagnoses for exactly this state
    # (`compute_production_vor:325`, `compute_bracket_sim:388`, `compute_player_signal:530`) and
    # ALL THREE ARE UNREACHABLE, because each one's unguarded `read_join_season` raises first. So
    # the fix is to refuse BEFORE the spine rather than to guard five reads: one refusal, in the
    # chain that knows why, instead of five guards in transforms that only know a file is missing.
    #
    # `SystemExit` on purpose — an AUTHORED refusal, so `worker_loop` lands it `rejected`
    # (terminal) rather than `failed` (retried three times). No retry can make a game happen.
    # Terminal is right and it is not a dead end: `jobs_active_league_idx` is partial on NON-
    # terminal states, so the moment their season starts the same person can link again and get a
    # fresh job. The refusal is terminal; the league is not.
    #
    # P5/S4f replaces this branch with a PENDING hold, so the user links once and the weekly
    # cadence picks the league up by itself. The predicate does not change — the branch does.
    if done + joined == 0:
        raise SystemExit(
            "this league has not played a week yet, so there is nothing to build from — no games "
            "means no rosters in motion, no results, and no projections to anchor.\n"
            "  Nothing is wrong with the league or with your account. Link it again once its "
            "first week is under way and it will build in about ten seconds.")

    # 3 · BAND — scoring-keyed and shared, and bounded by the honest-band season exactly as the
    # weekly refresh bounds it. Below 2026 it is a deliberate no-op, not a missing step. On a
    # worker `write_ros_player_band` VERIFIES rather than writes (P5/S3), so this can raise here.
    with stage("band"):
        if season >= build_db.FIRST_HONEST_BAND_SEASON:
            compute_ros_player_band.run(season, scoring_key=scoring_key)
            report["band"] = "rebuilt (shared substrate — NOT per-league cost)"
        else:
            report["band"] = f"skipped: season < FIRST_HONEST_BAND_SEASON ({build_db.FIRST_HONEST_BAND_SEASON})"
            print(f"  {report['band']}")

    # 4 · SPINE — the five decision reads. _compute_league accumulates its own per-read timing,
    # which is where the bracket_sim (10k sims PER as-of week) cost becomes visible.
    with stage("spine"):
        spine_timing: dict = defaultdict(float)
        compute_spine._compute_league(lid, season, scoring_key, spine_timing)
        report["spine_reads"] = {k: round(v, 2) for k, v in sorted(spine_timing.items(),
                                                                   key=lambda kv: -kv[1])}
        print("  " + "  ".join(f"{k}={v:.1f}s" for k, v in report["spine_reads"].items()))

    # 5 · SCHEDULE — the league-scoped schedule export the served store needs.
    with stage("schedule"):
        export_schedule.run(season, league_id=lid)

    # 6 · DOSSIERS (opt-in) — the Manager Dossier surface, which `_compute_league` does NOT cover.
    # It is a CROSS-LEAGUE fan-out: every manager's comparable other leagues, throttled, hundreds
    # of calls. P5/S0 measured it at 80s / 248 Sleeper calls and made it a DEFERRED job class, so
    # the onboarder never runs it — which is exactly why the catalog row sets panels_manager False.
    # The AI leg (write_manager_dossiers → one Haiku call per manager) is deliberately NOT run: the
    # manager count IS the call count, so it can be priced without spending.
    if dossiers:
        with stage("manager_activity"):
            if dl.manager_activity_exists(season, league_id=lid):
                print("  manager_activity already present — skipped (gate, not work)")
            else:
                sleeper.fetch_manager_activity(lid, season)
        with stage("manager_features"):
            compute_manager_features.run(season, league_id=lid)
        feats = dl.read_manager_features(season, league_id=lid)
        report["dossier_ai_calls"] = feats.height
        print(f"  {feats.height} managers → {feats.height} Haiku calls a dossier write would make "
              f"(NOT made here — counted so it can be priced)")
    return report


# --- the catalog row ------------------------------------------------------------------------------

def resolve_lineage_root(lid: str, summary: dict) -> tuple[str, str]:
    """The redraft chain's ROOT league_id, plus a one-line account of how it was resolved.

    `lineage_id` is defined as the earliest league in the chain, and the demo manifest is built that
    way (8 of its 31 rows are their own root). The tempting rule for a first connect —
    `lineage_id = league_id` — is *unstable*: the moment an earlier season is added, the root moves
    and every prior row has to be rewritten. So walk Sleeper's own `previous_league_id` to the end
    of the chain instead. That is stable regardless of what this store happens to hold, and it costs
    0–3 extra GETs on a path that already makes 30–250.

    Bounded at `_LINEAGE_MAX_HOPS` and tolerant of a dead link: a league deleted from Sleeper stops
    the walk, and the last id actually reached becomes the root. A store-rooted lineage IS unstable,
    so the reason is returned rather than swallowed — the caller prints it.
    """
    root, prev, hops = str(lid), summary.get("previous_league_id"), 0
    while prev and hops < _LINEAGE_MAX_HOPS:
        try:
            parent = sleeper.league_summary(prev)
        except Exception as exc:   # noqa: BLE001 — a deleted prior season is a stop, not a failure
            return root, (f"walk stopped at {prev} ({type(exc).__name__}) — rooted at {root}, which "
                          f"is STORE-ROOTED and will move if that season is ever recovered")
        if not parent.get("league_id"):
            break
        root, prev, hops = str(parent["league_id"]), parent.get("previous_league_id"), hops + 1
    if hops >= _LINEAGE_MAX_HOPS:
        return root, f"walk hit the {_LINEAGE_MAX_HOPS}-hop cap — rooted at {root} (may not be the true root)"
    if root == str(lid):
        return root, "no previous_league_id — this league IS the chain root"
    return root, f"walked {hops} season(s) back to the chain root"


def build_catalog_row(lid: str, season: int, scoring_key: str, summary: dict,
                      lineage_id: str) -> pl.DataFrame:
    """The twelve columns for one connected league. **The rule, then the application.**

        A panel flag is TRUE only if that read is honest for that slice today.

    Applied against what the chain actually produces — `season`, `teams`, `lineup_slots`,
    `league_settings`, `schedule` and the five spine reads — and nothing else:

    - `is_mine` FALSE. It is not the owner's league. It also cannot reach `build_db._ref()`, which
      reads `read_demo_manifest()` alone, so a connected row can never become the schema reference
      for the whole database — `_ref` now asserts exactly one row satisfies its filter.
    - `panels_market` FALSE. The market read is gated off everywhere (it prices today's market
      against a past season's rosters), and the chain produces no `market_vor` rows at all.
    - `panels_ros` FALSE. No `ros_synthesis`; and `compute_ros_league_view` takes no `league_id`
      parameter at all, so it is structurally an is_mine-only entity.
    - `panels_manager` FALSE, and this one is a DECISION against a measurement rather than a
      default. P5/S0 clocked the dossier fan-out at 80s / 248 Sleeper calls and made it a deferred
      job class; the onboard chain therefore does not run it, so there are no `manager_dossiers`
      rows for this league. A true flag would light a panel with nothing behind it — which is the
      failure this project keeps naming (a confident wrong answer beats nothing, never). S4b's
      deferred job flips this row to True when the dossiers exist, and the append writer replaces
      one row to do it.
    - `viewer_roster_id` NULL. The seat is a user × league property (`user_leagues.roster_id`) and
      acquiring it is S4b. NOTE for S4b: a null seat makes `reads.resolve_viewer` fall back to
      matching MY_USERNAME against `teams.owner_name`. On a stranger's league that normally matches
      nothing → no "you" highlight, degraded but not wrong. If the owner's own handle IS in the
      connected league, that roster is silently highlighted as the *stranger's* "you", and nothing
      checks the roster belongs to the caller.
    """
    n_teams = summary.get("total_rosters")
    if n_teams is None:
        n_teams = dl.read_sleeper_teams(season, league_id=lid).height
    return pl.DataFrame([{
        "lineage_id": str(lineage_id),
        "league_id": str(lid),
        "season": int(season),
        "name": summary.get("name") or f"League {lid}",
        "scoring_key": str(scoring_key),
        "num_teams": int(n_teams),
        "is_mine": False,
        "previous_league_id": summary.get("previous_league_id"),
        "viewer_roster_id": None,
        "panels_market": False,
        "panels_ros": False,
        "panels_manager": False,
    }], schema=dl.read_demo_manifest().schema)


# --- the caller's seat ----------------------------------------------------------------------------

def resolve_seat(lid: str, season: int, owner_id: str | None) -> int | None:
    """Which roster in this league belongs to `owner_id` — the "you" highlight (P5/S4c).

    **The brief for this session said `_roster_for_owner(rosters, owner_id)` costs no extra Sleeper
    call because "the worker fetches rosters anyway". It does not RETAIN them.** `fetch_teams` reads
    `/league/{id}/rosters` transiently for a name lookup and persists only `teams_{year}.parquet`;
    and on a `resume` or `reonboard` run the fetch stage is skipped entirely, so there is no rosters
    payload in memory at all. Calling it directly would mean a fresh GET on every job.

    **The genuinely zero-call path is that parquet**, which already carries `owner_id` per
    `roster_id` — persisted since Session 3a precisely because it is the identity join key. So:

    1. the teams parquet — no network, and it answers for every league's primary owners;
    2. failing that, ONE `/rosters` GET through `sleeper._roster_for_owner`, which is the only
       thing that covers **co-owners** (the parquet records `owner_id` alone, so a co-owner's seat
       is simply not in it).

    **A miss is not an error.** Nobody has to hold a seat in a league they linked — the direct
    league-id path carries no handle at all, and that is a supported way to use this (settled with
    Will, 2026-08-14: there is no ownership verification, so "I can see this league" and "I play in
    it" are deliberately different questions). A null seat renders as no "you" highlight, which is
    exactly what `reads.resolve_viewer` now produces for a connected league.
    """
    if not owner_id:
        return None
    owner = str(owner_id)

    try:
        teams = dl.read_sleeper_teams(season, league_id=lid)
        if "owner_id" in teams.columns:
            hit = teams.filter(pl.col("owner_id").cast(pl.Utf8) == owner)
            if hit.height:
                return int(hit["roster_id"][0])
    except Exception as exc:      # noqa: BLE001 — an unreadable parquet falls through to the GET
        print(f"  seat: teams parquet unusable ({type(exc).__name__}: {exc}) — asking Sleeper")

    try:
        rosters = sleeper._get_json(f"{sleeper._SLEEPER_BASE}/league/{lid}/rosters") or []
    except Exception as exc:      # noqa: BLE001 — a seat is not worth failing a built league over
        print(f"  seat: could not read rosters ({type(exc).__name__}: {exc}) — no seat recorded")
        return None
    rid = sleeper._roster_for_owner(rosters, owner)
    if rid is not None:
        print(f"  seat: resolved roster {rid} as a CO-OWNER (one extra Sleeper call)")
    return int(rid) if rid is not None else None


# --- the entry point ------------------------------------------------------------------------------

def assert_in_scope(lid: str, summary: dict) -> None:
    """V1 is redraft only (CODING_BIBLE §4) — decline out-of-scope shapes, never mis-handle them.

    Sleeper's `settings.type` is 0/1/2 = redraft/keeper/dynasty. **Absence is not redraft**: the
    corpus recovery found 7 known keeper/dynasty leagues with the key missing, so an unknown type
    refuses too. The other two V1 constraints police themselves — an unscoreable custom scoring
    profile yields a `cust-*` key with no `projection_consensus`, which the substrate assertion
    already raises on, and 1QB/superflex are both in scope.

    This is the loud stop, not the product's answer. S5 owns the graceful user-facing rejection.

    **The lifecycle rule is THE SAME FUNCTION the API greys the button with** (P5/S4d):
    `platforms.league_has_started`. It is authoritative *here* rather than there, because
    `platforms.classify` is advisory by its own docstring and `POST /api/connect` runs no
    classification at all on a pasted league id — so the worker is the only place that has to be
    right. It costs no extra Sleeper call: `status` is already on the `summary` dict the caller
    fetched one line above. P5/S4f swaps this refusal for a `pending` hold, reusing the predicate.
    """
    t = summary.get("league_type")
    if t != "redraft":
        raise SystemExit(
            f"league {lid} is {t or 'of unknown type'} (Sleeper settings.type={summary.get('raw_type')!r}) "
            f"— V1 supports REDRAFT only.\n"
            "  Absence of the key is NOT treated as redraft: known keeper/dynasty leagues omit it, "
            "and guessing here would mis-score somebody's season.")

    started, why = platforms.league_has_started(summary)
    if not started:
        raise SystemExit(
            f"{why}, so this league has no rosters yet and there is nothing to build from.\n"
            "  Nothing is wrong with the league or with your account. Link it again once your "
            "draft is done and the season is under way.")


def onboard(lid: str, season: int, *, to_week: int | None = None, do_load: bool = True,
            dry_run: bool = False, stage=_print_stage) -> dict:
    """Onboard one league end to end: chain → catalog row → load that COMMITS.

    The order is load-bearing. The catalog parquet is written BEFORE the load because
    `build_db.load_league` resolves its slices from `_catalog()` — the league has to be catalogued
    for the loader to agree it exists. The Postgres catalog row then goes in inside the load's own
    transaction (`catalog=True`), so discoverability and readability commit together.

    `stage` is the same observer `run_chain` already took, now threaded through the whole entry
    point (P5/S4b) — including the two steps that were outside it, the preflight and the load. The
    worker passes one that writes the job's state into Postgres, so the states a reader sees come
    from THE chain rather than from a second description of it that could drift. `bench_cold_league`
    still calls `run_chain` directly with its timing observer; nothing about it changes.
    """
    lid = str(lid)
    report: dict = {"league_id": lid, "season": season, "to_week": to_week, "stages": {}}

    # Everything that decides whether this league may be onboarded at all, inside one stage. S5 adds
    # its preflight here; today it is coldness, scope and the season match. Every refusal in this
    # block is deterministic — retrying cannot change the answer — which is what makes it the
    # `rejected` boundary for the queue.
    with stage("validating"):
        state = classify(lid, season)
        report["state"] = state
        print(f"onboarding {lid} ({season}) — state: {state.upper()}")

        summary = sleeper.league_summary(lid)
        assert_in_scope(lid, summary)
        if summary.get("season") is not None and int(summary["season"]) != int(season):
            raise SystemExit(f"league {lid} is Sleeper season {summary['season']}, not {season}. "
                             "A Sleeper league_id belongs to exactly one season.")
        lineage_id, how = resolve_lineage_root(lid, summary)
        report["lineage_id"], report["lineage_rule"] = lineage_id, how
        print(f"  name={summary.get('name')!r}  teams={summary.get('total_rosters')}  "
              f"type={summary.get('league_type')}\n  lineage_id={lineage_id} ({how})")

    run_chain(lid, season, to_week=to_week, report=report, stage=stage)
    row = build_catalog_row(lid, season, report["scoring_key"], summary, lineage_id)
    report["catalog_row"] = row.row(0, named=True)
    print("\n--- catalog row ---")
    for k, v in report["catalog_row"].items():
        print(f"  {k:20s} {v!r}")

    if dry_run:
        print("\n--dry-run: nothing catalogued, nothing loaded.")
        return report

    # The catalog write and the Postgres load are ONE stage, because they are one commitment: the
    # parquet row is what makes `load_league` agree the league exists, and the Postgres catalog row
    # goes in inside the load's own transaction. A crash between them is the resumable window that
    # `classify` returns `resume` for.
    with stage("loading"):
        dl.write_connected_league(row, lid, season)
        print(f"✓ connected_catalog.parquet now holds {dl.read_connected_catalog().height} row(s)")

        if do_load:
            with psycopg.connect(database_url()) as conn:
                counts = build_db.load_league(conn, lid, catalog=True)
            report["load"] = counts
            total = sum(v for k, v in counts.items() if k != "league_catalog")
            print(f"✓ COMMITTED {total} rows across "
                  f"{len([k for k in counts if k != 'league_catalog'])} "
                  f"table(s) + {counts.get('league_catalog', 0)} catalog row; every other league untouched")
            for ds in build_db.DATASETS:
                if counts.get(ds.table):
                    print(f"    {ds.table:22s} {counts[ds.table]:>6d} rows")
        else:
            print("--no-load: the derived store and the catalog parquet are written; Postgres is not.")
    return report


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--league", required=True, help="the Sleeper league_id to onboard")
    ap.add_argument("--season", type=int, required=True)
    ap.add_argument("--to-week", type=int, default=None,
                    help="cap join+spine at this week (models an early-season connect)")
    ap.add_argument("--no-load", action="store_true", help="build + catalog, but do not write Postgres")
    ap.add_argument("--dry-run", action="store_true",
                    help="run the chain and print the catalog row; write neither it nor Postgres")
    a = ap.parse_args()
    onboard(a.league, a.season, to_week=a.to_week, do_load=not a.no_load, dry_run=a.dry_run)


if __name__ == "__main__":
    main()
