"""Onboard a league the store has never seen — the real entry point (P5/S4a).

`weekly_refresh` ADVANCES a league that is already in the store. `bench_cold_league` MEASURES the
other half and then deliberately throws it away. This is the half that keeps what it built.

**Why this module exists at all.** Until now nothing in this system had ever catalogued a league.
`build_db._catalog()` was the frozen 31-row corpus slate plus the one generated demo clone;
`load_league` refuses anything absent from it in as many words ("cataloging a brand-new league is
onboarding/P5, not the scoped reload"); and `bench_cold_league` rolls its load back specifically to
sidestep that gate, saying in its own docstring that "there is no single 'onboard a cold league'
entry point today. P5/S4 needs a real one; this composes the same steps in the same order
meanwhile." This is that entry point, and it composes nothing new.

**ONE CHAIN, NOT TWO.** `run_chain` below is the chain — fetch raw → resolve the scoring key from
THIS league's own settings → assert the substrate → join every week → band (season-gated) → spine →
schedule. `bench_cold_league` imports it and wraps each step in timing; this module wraps it in a
catalog write and a COMMIT. If the benchmark and the onboarder ever became two implementations of
the same sequence, the 8.4–10.3s P5/S0 measured would quietly stop describing what actually runs.
The seam is the `stage` argument: a factory returning a context manager per step. The benchmark
passes its `_Stage`; this module passes a printer.

**What it refuses, loudly.** A league outside V1's scope (not redraft), a league that is the first
on its scoring key (no `projection_consensus` — CODING_BIBLE §4: never silently mis-score), and a
league that belongs to another layer (the frozen corpus, the demo slate, the generated clone). It
does NOT refuse a league already in `connected_catalog` — that is a re-onboard, and it is required
to be a clean no-op.

    python -m application.data.serve.onboard_league --league <id> --season 2025 --dry-run
    python -m application.data.serve.onboard_league --league <id> --season 2025
"""

from __future__ import annotations

import argparse
import contextlib
from collections import defaultdict
from pathlib import Path

import polars as pl
import psycopg

from application.api.db import database_url
from application.data import data_layer as dl
from application.data.corpus import compute_spine, harvest
from application.data.fetchers import sleeper
from application.data.serve import build_db
from application.data.transforms import (compute_manager_features, compute_ros_player_band,
                                         export_schedule, join_nfl_sleeper_weekly)
from application.data.transforms._keys import scoring_key_from_settings

_LINEAGE_MAX_HOPS = 10


# --- where a league may already live -------------------------------------------------------------

def _league_dirs(lid: str, season: int) -> dict[str, Path]:
    """Every directory a league-scoped run writes — the growth measurement, the teardown and the
    coldness check all read this, so they can't drift apart."""
    return {"raw_sleeper": dl._sleeper_league_dir(season, lid),
            "joined": dl._join_league_dir(lid),
            "derived": dl._league_dir(lid)}


def assert_cold(lid: str, season: int) -> None:
    """A league is cold when the store has never seen it: absent from the registry, absent from
    EVERY catalog (all three served ones plus the frozen corpus manifest), and absent from all three
    on-disk league directories. Standing rule 1 in executable form — a fast total is a bug until
    this has passed, and the onboarder uses it as a precondition rather than a benchmark aid.

    It is also the "catalogued after" half of S4a's DoD: once `write_connected_league` has run, this
    function must REFUSE the same league. A coldness check that misses a catalog is a coldness check
    that lies, and until S4a it missed two."""
    warm = []
    # A synthetic league is generated, not harvested (P5/S2d), so "cold" is not even the right
    # question — there is nothing on Sleeper to fetch. Its on-disk directories would already trip
    # the check below, but incidentally rather than for a stated reason; this says the reason.
    if dl.is_synthetic(lid):
        raise SystemExit(
            f"league {lid} is SYNTHETIC — generated by build_demo_clone, not harvested from Sleeper. "
            "There is no cold load to run.")
    if dl.leagues_exists():
        if dl.read_leagues().filter(pl.col("league_id").cast(str) == lid).height:
            warm.append("leagues.parquet")
    # EVERY catalog, not just the demo manifest. `_catalog()` is the union of three parquets, so a
    # coldness check that reads one of them is a coldness check that lies — and it lied by two.
    # `synthetic_catalog` was never checked: the `is_synthetic` short-circuit above only covers the
    # hardcoded SYNTHETIC_LEAGUE_IDS literal, so a second clone would have slipped straight through.
    # `connected_catalog` is new in S4a and is the one that will actually fill up.
    for label, exists, read in (("demo_manifest.parquet", dl.demo_manifest_exists, dl.read_demo_manifest),
                                ("synthetic_catalog.parquet", dl.synthetic_catalog_exists, dl.read_synthetic_catalog),
                                ("connected_catalog.parquet", dl.connected_catalog_exists, dl.read_connected_catalog)):
        if exists() and read().filter(pl.col("league_id").cast(str) == lid).height:
            warm.append(label)
    # The frozen corpus manifest is not a served catalog, but a corpus league is emphatically not
    # cold — the spine ran on 269 of them — and its artifacts may have been swept while its manifest
    # row survived. Checking it here is what stops a "cold" run from being aimed at the corpus.
    if dl.corpus_manifest_exists():
        if dl.read_corpus_manifest().filter(pl.col("league_id").cast(str) == lid).height:
            warm.append("corpus_manifest.parquet (the frozen 271-league corpus)")
    warm += [f"{k} ({p})" for k, p in _league_dirs(lid, season).items() if p.exists()]
    if warm:
        raise SystemExit(
            f"league {lid} is NOT cold — present in: {', '.join(warm)}.\n"
            "Timing or onboarding a warm league measures the pipeline's per-step gates, not the "
            "work. Pick a league the store has never seen (do NOT delete an existing one's "
            "artifacts — that risks the frozen corpus and the demo slate).")


def classify(lid: str, season: int) -> str:
    """`cold` (never seen), `reonboard` (already connected), or raise (it belongs to another layer).

    A flag would have been simpler and wrong. "Is this a re-onboard?" is a fact about the store, not
    an assertion the caller gets to make, and the three outcomes are genuinely different: a cold
    league must do all the work, a re-onboard must be a clean no-op (DoD clause 4), and a league
    that is part of the frozen corpus or the demo slate must never be reachable from here at all —
    that is how you overwrite a fixture the L2 ledger is derived from.
    """
    lid = str(lid)
    if dl.connected_catalog_exists():
        if dl.read_connected_catalog().filter(pl.col("league_id").cast(str) == lid).height:
            return "reonboard"
    assert_cold(lid, season)
    return "cold"


# --- the chain ------------------------------------------------------------------------------------

@contextlib.contextmanager
def _print_stage(name: str):
    """The default stage observer: announce the step and nothing else. `bench_cold_league` passes a
    timing one instead, which is the only difference between measuring this chain and running it."""
    print(f"\n--- {name} ---")
    yield


def run_chain(lid: str, season: int, *, to_week: int | None, report: dict,
              stage=_print_stage, dossiers: bool = False) -> dict:
    """THE cold chain, in the real order, shared by the benchmark and the onboarder.

    Fills `report` in place and returns it. Every key it writes is consumed by
    `bench_cold_league.print_table` and by its `--json` output, so the names are a published
    interface — S0's numbers are keyed on them and S3 re-ran the benchmark to compare two machines.

    It does not touch Postgres and does not write a catalog row: this is the part that is identical
    whether you are measuring or committing.
    """
    # 1 · FETCH — the raw layer, exactly as the harvest pulls it (config → roster_positions →
    # lineup_slots → teams → every completed week's matchups + transactions). Gated on
    # `_raw_present` for the same reason harvest gates it: a re-run must not re-pull.
    with stage("fetch"):
        if harvest._raw_present(lid, season):
            print("  raw already present — skipped (this is the GATE, not the work)")
            report["fetch"] = "skipped (raw present)"
        else:
            harvest._pull_raw(lid, season)

    # The scoring key comes from THIS league's own settings. weekly_refresh._resolve_scoring_key
    # used to fall back to the is_mine league's key for anything absent from the catalog, which
    # would silently score a stranger's league on the owner's profile — never let a cold league
    # take that path. (S4a fixed that fallback; this call is what it was fixed to.)
    scoring_key = scoring_key_from_settings(dl.read_scoring_settings(season, league_id=lid))
    report["scoring_key"] = scoring_key
    substrate = dl._projection_consensus_path(season, scoring_key)
    report["substrate_present"] = substrate.exists()
    print(f"\nscoring_key = {scoring_key}   substrate present: {report['substrate_present']}")
    if not report["substrate_present"]:
        raise SystemExit(
            f"no {season} projection_consensus for scoring_key {scoring_key} ({substrate}).\n"
            "This league is the first on its key — build the substrate first "
            "(bench_cold_league --substrate). Onboarding it anyway would score it against another "
            "league's profile, which CODING_BIBLE §4 forbids: never silently mis-score.")

    reg_end = harvest._reg_end(lid, season)
    target = min(reg_end, to_week) if to_week else reg_end
    report["reg_end"], report["target_week"] = reg_end, target
    print(f"regular season ends wk{reg_end}; joining + computing through wk{target}")

    # 2 · JOIN — one week at a time, the authoritative player×week table. Starts after the
    # deepest week already joined, exactly like weekly_refresh, so a re-run is a no-op.
    with stage("join"):
        jp = dl._join_season_path(season, lid)
        done = int(pl.read_parquet(jp, columns=["week"])["week"].max()) if jp.exists() else 0
        joined = 0
        for wk in range(done + 1, target + 1):
            if dl._sleeper_matchups_path(season, wk, lid).exists():
                join_nfl_sleeper_weekly.run(season, wk, league_id=lid)
                joined += 1
        report["weeks_joined"] = joined
        report["weeks_already_joined"] = done

    # 3 · BAND — scoring-keyed and shared, and bounded by the honest-band season exactly as the
    # weekly refresh bounds it. Below 2026 it is a deliberate no-op, not a missing step. On a
    # worker `write_ros_player_band` VERIFIES rather than writes (P5/S3), so this can raise here.
    with stage("band"):
        if season >= build_db.FIRST_HONEST_BAND_SEASON:
            compute_ros_player_band.run(season, scoring_key=scoring_key)
            report["band"] = "rebuilt (shared substrate — NOT per-league cost)"
        else:
            report["band"] = f"skipped: season < FIRST_HONEST_BAND_SEASON ({build_db.FIRST_HONEST_BAND_SEASON})"
            print(f"  {report['band']}")

    # 4 · SPINE — the five decision reads. _compute_league accumulates its own per-read timing,
    # which is where the bracket_sim (10k sims PER as-of week) cost becomes visible.
    with stage("spine"):
        spine_timing: dict = defaultdict(float)
        compute_spine._compute_league(lid, season, scoring_key, spine_timing)
        report["spine_reads"] = {k: round(v, 2) for k, v in sorted(spine_timing.items(),
                                                                   key=lambda kv: -kv[1])}
        print("  " + "  ".join(f"{k}={v:.1f}s" for k, v in report["spine_reads"].items()))

    # 5 · SCHEDULE — the league-scoped schedule export the served store needs.
    with stage("schedule"):
        export_schedule.run(season, league_id=lid)

    # 6 · DOSSIERS (opt-in) — the Manager Dossier surface, which `_compute_league` does NOT cover.
    # It is a CROSS-LEAGUE fan-out: every manager's comparable other leagues, throttled, hundreds
    # of calls. P5/S0 measured it at 80s / 248 Sleeper calls and made it a DEFERRED job class, so
    # the onboarder never runs it — which is exactly why the catalog row sets panels_manager False.
    # The AI leg (write_manager_dossiers → one Haiku call per manager) is deliberately NOT run: the
    # manager count IS the call count, so it can be priced without spending.
    if dossiers:
        with stage("manager_activity"):
            if dl.manager_activity_exists(season, league_id=lid):
                print("  manager_activity already present — skipped (gate, not work)")
            else:
                sleeper.fetch_manager_activity(lid, season)
        with stage("manager_features"):
            compute_manager_features.run(season, league_id=lid)
        feats = dl.read_manager_features(season, league_id=lid)
        report["dossier_ai_calls"] = feats.height
        print(f"  {feats.height} managers → {feats.height} Haiku calls a dossier write would make "
              f"(NOT made here — counted so it can be priced)")
    return report


# --- the catalog row ------------------------------------------------------------------------------

def resolve_lineage_root(lid: str, summary: dict) -> tuple[str, str]:
    """The redraft chain's ROOT league_id, plus a one-line account of how it was resolved.

    `lineage_id` is defined as the earliest league in the chain, and the demo manifest is built that
    way (8 of its 31 rows are their own root). The tempting rule for a first connect —
    `lineage_id = league_id` — is *unstable*: the moment an earlier season is added, the root moves
    and every prior row has to be rewritten. So walk Sleeper's own `previous_league_id` to the end
    of the chain instead. That is stable regardless of what this store happens to hold, and it costs
    0–3 extra GETs on a path that already makes 30–250.

    Bounded at `_LINEAGE_MAX_HOPS` and tolerant of a dead link: a league deleted from Sleeper stops
    the walk, and the last id actually reached becomes the root. A store-rooted lineage IS unstable,
    so the reason is returned rather than swallowed — the caller prints it.
    """
    root, prev, hops = str(lid), summary.get("previous_league_id"), 0
    while prev and hops < _LINEAGE_MAX_HOPS:
        try:
            parent = sleeper.league_summary(prev)
        except Exception as exc:   # noqa: BLE001 — a deleted prior season is a stop, not a failure
            return root, (f"walk stopped at {prev} ({type(exc).__name__}) — rooted at {root}, which "
                          f"is STORE-ROOTED and will move if that season is ever recovered")
        if not parent.get("league_id"):
            break
        root, prev, hops = str(parent["league_id"]), parent.get("previous_league_id"), hops + 1
    if hops >= _LINEAGE_MAX_HOPS:
        return root, f"walk hit the {_LINEAGE_MAX_HOPS}-hop cap — rooted at {root} (may not be the true root)"
    if root == str(lid):
        return root, "no previous_league_id — this league IS the chain root"
    return root, f"walked {hops} season(s) back to the chain root"


def build_catalog_row(lid: str, season: int, scoring_key: str, summary: dict,
                      lineage_id: str) -> pl.DataFrame:
    """The twelve columns for one connected league. **The rule, then the application.**

        A panel flag is TRUE only if that read is honest for that slice today.

    Applied against what the chain actually produces — `season`, `teams`, `lineup_slots`,
    `league_settings`, `schedule` and the five spine reads — and nothing else:

    - `is_mine` FALSE. It is not the owner's league. It also cannot reach `build_db._ref()`, which
      reads `read_demo_manifest()` alone, so a connected row can never become the schema reference
      for the whole database — `_ref` now asserts exactly one row satisfies its filter.
    - `panels_market` FALSE. The market read is gated off everywhere (it prices today's market
      against a past season's rosters), and the chain produces no `market_vor` rows at all.
    - `panels_ros` FALSE. No `ros_synthesis`; and `compute_ros_league_view` takes no `league_id`
      parameter at all, so it is structurally an is_mine-only entity.
    - `panels_manager` FALSE, and this one is a DECISION against a measurement rather than a
      default. P5/S0 clocked the dossier fan-out at 80s / 248 Sleeper calls and made it a deferred
      job class; the onboard chain therefore does not run it, so there are no `manager_dossiers`
      rows for this league. A true flag would light a panel with nothing behind it — which is the
      failure this project keeps naming (a confident wrong answer beats nothing, never). S4b's
      deferred job flips this row to True when the dossiers exist, and the append writer replaces
      one row to do it.
    - `viewer_roster_id` NULL. The seat is a user × league property (`user_leagues.roster_id`) and
      acquiring it is S4b. NOTE for S4b: a null seat makes `reads.resolve_viewer` fall back to
      matching MY_USERNAME against `teams.owner_name`. On a stranger's league that normally matches
      nothing → no "you" highlight, degraded but not wrong. If the owner's own handle IS in the
      connected league, that roster is silently highlighted as the *stranger's* "you", and nothing
      checks the roster belongs to the caller.
    """
    n_teams = summary.get("total_rosters")
    if n_teams is None:
        n_teams = dl.read_sleeper_teams(season, league_id=lid).height
    return pl.DataFrame([{
        "lineage_id": str(lineage_id),
        "league_id": str(lid),
        "season": int(season),
        "name": summary.get("name") or f"League {lid}",
        "scoring_key": str(scoring_key),
        "num_teams": int(n_teams),
        "is_mine": False,
        "previous_league_id": summary.get("previous_league_id"),
        "viewer_roster_id": None,
        "panels_market": False,
        "panels_ros": False,
        "panels_manager": False,
    }], schema=dl.read_demo_manifest().schema)


# --- the entry point ------------------------------------------------------------------------------

def assert_in_scope(lid: str, summary: dict) -> None:
    """V1 is redraft only (CODING_BIBLE §4) — decline out-of-scope shapes, never mis-handle them.

    Sleeper's `settings.type` is 0/1/2 = redraft/keeper/dynasty. **Absence is not redraft**: the
    corpus recovery found 7 known keeper/dynasty leagues with the key missing, so an unknown type
    refuses too. The other two V1 constraints police themselves — an unscoreable custom scoring
    profile yields a `cust-*` key with no `projection_consensus`, which the substrate assertion
    already raises on, and 1QB/superflex are both in scope.

    This is the loud stop, not the product's answer. S5 owns the graceful user-facing rejection.
    """
    t = summary.get("league_type")
    if t != "redraft":
        raise SystemExit(
            f"league {lid} is {t or 'of unknown type'} (Sleeper settings.type={summary.get('raw_type')!r}) "
            f"— V1 supports REDRAFT only.\n"
            "  Absence of the key is NOT treated as redraft: known keeper/dynasty leagues omit it, "
            "and guessing here would mis-score somebody's season.")


def onboard(lid: str, season: int, *, to_week: int | None = None, do_load: bool = True,
            dry_run: bool = False) -> dict:
    """Onboard one league end to end: chain → catalog row → load that COMMITS.

    The order is load-bearing. The catalog parquet is written BEFORE the load because
    `build_db.load_league` resolves its slices from `_catalog()` — the league has to be catalogued
    for the loader to agree it exists. The Postgres catalog row then goes in inside the load's own
    transaction (`catalog=True`), so discoverability and readability commit together.
    """
    lid = str(lid)
    state = classify(lid, season)
    report: dict = {"league_id": lid, "season": season, "to_week": to_week,
                    "state": state, "stages": {}}
    print(f"onboarding {lid} ({season}) — state: {state.upper()}")

    summary = sleeper.league_summary(lid)
    assert_in_scope(lid, summary)
    if summary.get("season") is not None and int(summary["season"]) != int(season):
        raise SystemExit(f"league {lid} is Sleeper season {summary['season']}, not {season}. "
                         "A Sleeper league_id belongs to exactly one season.")
    lineage_id, how = resolve_lineage_root(lid, summary)
    report["lineage_id"], report["lineage_rule"] = lineage_id, how
    print(f"  name={summary.get('name')!r}  teams={summary.get('total_rosters')}  "
          f"type={summary.get('league_type')}\n  lineage_id={lineage_id} ({how})")

    run_chain(lid, season, to_week=to_week, report=report)
    row = build_catalog_row(lid, season, report["scoring_key"], summary, lineage_id)
    report["catalog_row"] = row.row(0, named=True)
    print("\n--- catalog row ---")
    for k, v in report["catalog_row"].items():
        print(f"  {k:20s} {v!r}")

    if dry_run:
        print("\n--dry-run: nothing catalogued, nothing loaded.")
        return report

    dl.write_connected_league(row, lid, season)
    print(f"\n✓ connected_catalog.parquet now holds {dl.read_connected_catalog().height} row(s)")

    if do_load:
        with psycopg.connect(database_url()) as conn:
            counts = build_db.load_league(conn, lid, catalog=True)
        report["load"] = counts
        total = sum(v for k, v in counts.items() if k != "league_catalog")
        print(f"✓ COMMITTED {total} rows across {len([k for k in counts if k != 'league_catalog'])} "
              f"table(s) + {counts.get('league_catalog', 0)} catalog row; every other league untouched")
        for ds in build_db.DATASETS:
            if counts.get(ds.table):
                print(f"    {ds.table:22s} {counts[ds.table]:>6d} rows")
    else:
        print("--no-load: the derived store and the catalog parquet are written; Postgres is not.")
    return report


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--league", required=True, help="the Sleeper league_id to onboard")
    ap.add_argument("--season", type=int, required=True)
    ap.add_argument("--to-week", type=int, default=None,
                    help="cap join+spine at this week (models an early-season connect)")
    ap.add_argument("--no-load", action="store_true", help="build + catalog, but do not write Postgres")
    ap.add_argument("--dry-run", action="store_true",
                    help="run the chain and print the catalog row; write neither it nor Postgres")
    a = ap.parse_args()
    onboard(a.league, a.season, to_week=a.to_week, do_load=not a.no_load, dry_run=a.dry_run)


if __name__ == "__main__":
    main()
