-- App-side tables the loader can't reach (P5/S1, extended S1b and S2a).
-- Applied by `python -m application.api.init_auth_schema`.
--
-- DELIBERATELY NOT IN application/data/serve/schema.sql, and this is the load-bearing point:
-- that file is GENERATED by `build_db.py --emit` (which rewrites it wholesale, deleting any
-- hand-edit) and applied by `--load`, which DROPs every table it names. A table that is not
-- named there is structurally unreachable by the loader — protected by how the code works
-- rather than by anyone remembering.
--
-- That hazard is not hypothetical. `ros_player_band` today has RLS disabled while the other
-- 13 served tables have it enabled: RLS was turned on by hand, then that table was added by a
-- later --emit/--load and came back without it. Any out-of-band property on a schema.sql
-- table — RLS, a grant, a trigger, a foreign key — is destroyed by the next full load.
--
-- Idempotent: re-running is a no-op, matching the project's norm (load_league,
-- reload_manifest, weekly_refresh are all safely re-runnable).

CREATE TABLE IF NOT EXISTS public.app_users (
    -- The Supabase auth user id (the token's `sub`). ON DELETE CASCADE so removing someone
    -- from the project removes their profile rather than orphaning it.
    id          uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    email       text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    -- The pilot cohort tag. `leagues.parquet` already carries an unused `pilot_cohort` hook
    -- for exactly this; kept nullable because S1 has no cohort policy — S2/S4 decide that.
    cohort      text
);

-- Defense-in-depth only, and stated as such: the app connects as an owner role that BYPASSES
-- RLS, so this denies nothing to this API. It matters if the Data API is ever re-enabled or a
-- non-owner role ever connects. Real per-user isolation is API-layer work, and it is S2's.
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;


-- Signup attempts (P5/S1b) — the rate limiter's state.
--
-- IN POSTGRES, NOT IN MEMORY, and that is forced by the deployment shape rather than taste.
-- fly.toml sets `min_machines_running = 0` with `auto_stop_machines = "stop"`, so an in-process
-- dict is ERASED whenever a machine scales to zero — which makes the limiter defeatable on
-- purpose by simply waiting out the idle window. A limiter you can reset by being patient is not
-- a limiter. (S1b's audit corrected the citation this comment used to carry: fly.toml declares a
-- single `[[vm]]` block and no machine COUNT — the count is a deploy-time property, `fly scale
-- show`, not a config-file one. Scale-to-zero alone carries the decision; running more than one
-- machine only widens the same hole by splitting the budget across them.)
--
-- What it is really defending: the access code is chosen to be sayable out loud, so it is
-- low-entropy by construction. The rate limit is what makes that safe — brute-force resistance
-- first, protection of the email send budget second.
--
-- Rows are disposable; anything outside the window is noise. `at` is indexed because every
-- lookup is "attempts since T".
CREATE TABLE IF NOT EXISTS public.signup_attempts (
    id      bigserial PRIMARY KEY,
    email   text,
    ip      text,
    ok      boolean NOT NULL DEFAULT false,   -- did the code check pass (for triage, not policy)
    at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS signup_attempts_at_idx ON public.signup_attempts (at);
CREATE INDEX IF NOT EXISTS signup_attempts_email_at_idx ON public.signup_attempts (email, at);
CREATE INDEX IF NOT EXISTS signup_attempts_ip_at_idx ON public.signup_attempts (ip, at);

ALTER TABLE public.signup_attempts ENABLE ROW LEVEL SECURITY;


-- League ownership (P5/S2a) — the table that makes an account MEAN something.
--
-- Half of the one visibility predicate the whole app answers:
--     visible(league) = (league_id = DEMO_LEAGUE_ID)  OR  (owned by caller AND season = current)
-- The demo half is CONFIG (`settings.demo_league_id()`), deliberately not a row here: with exactly
-- one public league a table buys nothing, and a config value cannot drift from a loader-generated
-- artifact the way a seeded row can.
--
-- No `season` column, and that is on purpose. A redraft `league_id` already pins exactly one
-- (league, season) slice, so a season here would be a second copy of a fact `demo_manifest`
-- already holds — and the two would eventually disagree. The current-season term is applied at
-- read time by joining the catalog, not by trusting a denormalised column.
--
-- ON DELETE CASCADE for the same reason `app_users` has it: removing someone from the project
-- must not leave grants pointing at a user id that no longer exists.
--
-- What a row does NOT mean: that a human proved control of the address. S1b creates accounts with
-- `email_confirm: true` BEFORE the magic link is known to have sent, so a mailer failure leaves a
-- confirmed account behind (S1b audit, "Minor"). A grant is therefore an operator act about a
-- league, not evidence about a person. S4's connect flow writes the same row from the other
-- direction — a user claiming their own league — and that is where identity gets established.
CREATE TABLE IF NOT EXISTS public.user_leagues (
    user_id     uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    league_id   text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, league_id)
);

-- Same defense-in-depth caveat as above: the app connects as an owner role that BYPASSES RLS, so
-- this denies nothing to this API. Per-user isolation here is API-layer, by design (P5 settled).
ALTER TABLE public.user_leagues ENABLE ROW LEVEL SECURITY;

-- The viewer seat, as a USER × LEAGUE property (P5/S2b). Which roster is "you" was a property of
-- the *league* (`demo_manifest.viewer_roster_id`) — fine with one viewer, wrong the moment two
-- people share a league and each need their own highlight.
--
-- Nullable: a grant without a seat is normal (the operator may not know it, and S4's connect flow
-- learns it from Sleeper). Null falls back to `MY_USERNAME`, which is what keeps the demo's
-- behaviour exactly as it was.
--
-- THIS MUST BE AN EXPLICIT ALTER. `CREATE TABLE IF NOT EXISTS` above is a no-op on an existing
-- table, so a column added to that statement would silently never appear in any database that
-- already has the table — which is every database that matters. That is the S2a-audit F2 trap
-- ("a table that already existed in another shape keeps its old shape and nothing notices"), and
-- `init_auth_schema.verify()` now asserts this column is really present rather than trusting it.
ALTER TABLE public.user_leagues ADD COLUMN IF NOT EXISTS roster_id int;


-- The job queue (P5/S4b) — how work reaches the worker without a human running `fly ssh console`.
--
-- WHY A TABLE AND NOT AN HTTP CALL, so nobody redesigns this later. `api/requirements.txt` is
-- deliberately fastapi-only ("no polars/nflreadpy/anthropic") and `fly.worker.toml` declares NO
-- [http_service] — so the API cannot run a build, and cannot call the machine that can. The two
-- machines cannot talk to each other; they can both talk to Postgres. THAT, not latency, is the
-- forcing function: S0 measured a cold onboard at 8.4-10.3s, which would fit inside a request.
--
-- WHY THE STATE IS HERE rather than in the worker's process: the argument rate_limit.py:9-15 already
-- makes for `signup_attempts`, only sharper. In-process state is erased by every `fly deploy`, and
-- what this would lose is somebody's half-finished league.
--
-- And it is in THIS file rather than serve/schema.sql for the reason at the top of it: `--load`
-- DROPs every table it names, so a jobs table there would be destroyed by the next full load.
CREATE TABLE IF NOT EXISTS public.jobs (
    -- uuid, not bigserial, and the rule this file already follows is CLIENT-HELD -> uuid:
    -- `app_users.id` is uuid because a client holds it (the token's `sub`); `signup_attempts.id` is
    -- bigserial because nobody outside the server ever sees one. S4c puts this id in a URL
    -- (`GET /api/connect/{id}`), so a client holds it. Two reinforcing reasons: a sequential id is
    -- an enumeration oracle for VOLUME — how many leagues have connected, and how fast — even when
    -- S4c's authorization is correct, which is the objection S2b's identical-404 design exists for;
    -- and it removes the temptation to ORDER BY id, which breaks silently the first time a
    -- retry-after or priority column exists. The lease orders by `created_at`.
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The job class. Exactly one executor exists ('onboard'). The column is here anyway because the
    -- queue needs a second class before this brief's ink is dry — S4d enqueues the weekly refresh —
    -- and one column now beats a migration later on a file with no migration story. An unknown kind
    -- is REJECTED cleanly, never a crash: a crash loop on one malformed row is an outage for every
    -- other user's league. The Manager Dossier fan-out (80s / 248 Sleeper calls) is a DEFERRED job
    -- class and belongs to S4c, together with flipping `panels_manager` — that flag is False
    -- *because* the data does not exist, so it flips in the session that makes it true.
    kind              text NOT NULL DEFAULT 'onboard',

    -- The payload. `onboard_league.onboard(lid, season)` takes exactly these two, so a job is
    -- re-runnable from its own columns and nothing else.
    league_id         text NOT NULL,
    season            int  NOT NULL,

    -- queued -> validating -> fetching -> building -> loading -> ready | rejected | failed.
    -- The full set ships because S6's failure drills want it and a column is free. There are NO
    -- per-stage semantics and no per-stage UI: a ~10s build on a spinner does not need six
    -- user-visible states, and S4c decides what a person actually sees. `validating` is a SLOT —
    -- S5 owns preflight scope validation and the graceful rejection copy.
    --
    -- rejected vs failed is the distinction a reader must be able to make WITHOUT reading logs:
    --   rejected = a deliberate, deterministic refusal (out of scope, wrong season, unknown kind).
    --              Retrying cannot change the answer, so it is terminal on the first attempt.
    --   failed   = something went wrong (Sleeper, the network, a crash). Retryable, to the cap.
    state             text NOT NULL DEFAULT 'queued',
    error             text,

    -- Attribution. Nullable because S4b enqueues BY HAND and identity ACQUISITION is S4c's work;
    -- CASCADE for the same reason `app_users` and `user_leagues` have it — no record outlives its
    -- account. `init_auth_schema._CASCADE_FKS` asserts that, and had to learn about NULLs to do it.
    requested_by      uuid REFERENCES auth.users (id) ON DELETE CASCADE,

    -- The lease. IT MUST EXPIRE: without expiry a job killed mid-run holds its league until a human
    -- intervenes, which is the exact thing this table exists to remove. `leased_by` names the
    -- machine, so after a kill you can tell who was holding it. `attempts` caps the retries, so one
    -- poison row cannot loop for ever.
    attempts          int NOT NULL DEFAULT 0,
    leased_by         text,
    lease_expires_at  timestamptz,

    -- DoD 2: a reader can tell from the TABLE ALONE what happened and when, without the worker's
    -- stdout. `updated_at` is the FIRST in this repo — there is no existing convention and no
    -- trigger; every transition sets it in `job_queue.py`, i.e. in reviewable code rather than in
    -- invisible DDL (the same choice `app_users` made by writing its row from `/api/me`).
    created_at        timestamptz NOT NULL DEFAULT now(),
    started_at        timestamptz,
    finished_at       timestamptz,
    updated_at        timestamptz NOT NULL DEFAULT now()
);

-- THE STATE SET IS A CONSTRAINT, AND IT IS ADDED BY AN EXPLICIT ALTER. `CREATE TABLE IF NOT EXISTS`
-- above is a no-op on an existing table, so a CHECK written inside it would never land on any
-- database that already has the table — the same S2a-audit F2 trap `_ALTERED_COLUMNS` exists for,
-- one level down at the constraint. DROP-then-ADD keeps it idempotent AND makes adding S6's next
-- state a one-line edit that actually reaches production instead of silently not doing so.
ALTER TABLE public.jobs DROP CONSTRAINT IF EXISTS jobs_state_check;
ALTER TABLE public.jobs ADD CONSTRAINT jobs_state_check CHECK (state IN (
    'queued', 'validating', 'fetching', 'building', 'loading', 'ready', 'rejected', 'failed'));

-- The lease looks for the oldest leasable row, so it filters on state and orders by created_at.
CREATE INDEX IF NOT EXISTS jobs_state_created_at_idx ON public.jobs (state, created_at);

-- ONE ACTIVE JOB PER (league, season). `FOR UPDATE SKIP LOCKED` gives row-level exclusion, not
-- league-level: two active rows for one league would race on the same on-disk artifacts and on
-- `load_league`'s DELETE+COPY. It cannot happen TODAY — a Fly volume attaches to exactly one
-- machine, so the worker is a stateful singleton — but S4d adds a second producer and the GitHub
-- Actions runner is a third machine that already exists, so this is built as if it could.
-- Terminal rows are excluded, so re-submitting a finished league is still allowed.
CREATE UNIQUE INDEX IF NOT EXISTS jobs_active_league_idx ON public.jobs (league_id, season)
    WHERE state NOT IN ('ready', 'rejected', 'failed');

-- Same defense-in-depth caveat as every other table here: the app connects as an owner role that
-- BYPASSES RLS, so this denies nothing to this API.
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;


-- RETIRED IN P5/S2c: `public.nfl_state_cache`.
--
-- S2a resolved the current season from Sleeper's /v1/state/nfl and persisted a last-known-good
-- here, because `min_machines_running = 0` erases an in-process cache on every scale-to-zero. The
-- cache existed to survive a Sleeper outage; S2c derives the season from the calendar instead
-- (`settings.current_season`), so there is no outage left to survive and nothing left to cache.
--
-- Dropped here rather than by hand so the cleanup is idempotent, re-runnable and reviewable — the
-- same reason every other statement in this file is. Its only reader was deleted in the same
-- commit. Safe to delete this block once every environment has run it.
DROP TABLE IF EXISTS public.nfl_state_cache;
