-- App-side tables the loader can't reach (P5/S1, extended S1b and S2a).
-- Applied by `python -m application.api.init_auth_schema`.
--
-- DELIBERATELY NOT IN application/data/serve/schema.sql, and this is the load-bearing point:
-- that file is GENERATED by `build_db.py --emit` (which rewrites it wholesale, deleting any
-- hand-edit) and applied by `--load`, which DROPs every table it names. A table that is not
-- named there is structurally unreachable by the loader — protected by how the code works
-- rather than by anyone remembering.
--
-- That hazard is not hypothetical. `ros_player_band` today has RLS disabled while the other
-- 13 served tables have it enabled: RLS was turned on by hand, then that table was added by a
-- later --emit/--load and came back without it. Any out-of-band property on a schema.sql
-- table — RLS, a grant, a trigger, a foreign key — is destroyed by the next full load.
--
-- Idempotent: re-running is a no-op, matching the project's norm (load_league,
-- reload_manifest, weekly_refresh are all safely re-runnable).

CREATE TABLE IF NOT EXISTS public.app_users (
    -- The Supabase auth user id (the token's `sub`). ON DELETE CASCADE so removing someone
    -- from the project removes their profile rather than orphaning it.
    id          uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    email       text,
    created_at  timestamptz NOT NULL DEFAULT now(),
    -- The pilot cohort tag. `leagues.parquet` already carries an unused `pilot_cohort` hook
    -- for exactly this; kept nullable because S1 has no cohort policy — S2/S4 decide that.
    cohort      text
);

-- Defense-in-depth only, and stated as such: the app connects as an owner role that BYPASSES
-- RLS, so this denies nothing to this API. It matters if the Data API is ever re-enabled or a
-- non-owner role ever connects. Real per-user isolation is API-layer work, and it is S2's.
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;


-- Signup attempts (P5/S1b) — the rate limiter's state.
--
-- IN POSTGRES, NOT IN MEMORY, and that is forced by the deployment shape rather than taste.
-- fly.toml sets `min_machines_running = 0` with `auto_stop_machines = "stop"`, so an in-process
-- dict is ERASED whenever a machine scales to zero — which makes the limiter defeatable on
-- purpose by simply waiting out the idle window. A limiter you can reset by being patient is not
-- a limiter. (S1b's audit corrected the citation this comment used to carry: fly.toml declares a
-- single `[[vm]]` block and no machine COUNT — the count is a deploy-time property, `fly scale
-- show`, not a config-file one. Scale-to-zero alone carries the decision; running more than one
-- machine only widens the same hole by splitting the budget across them.)
--
-- What it is really defending: the access code is chosen to be sayable out loud, so it is
-- low-entropy by construction. The rate limit is what makes that safe — brute-force resistance
-- first, protection of the email send budget second.
--
-- Rows are disposable; anything outside the window is noise. `at` is indexed because every
-- lookup is "attempts since T".
CREATE TABLE IF NOT EXISTS public.signup_attempts (
    id      bigserial PRIMARY KEY,
    email   text,
    ip      text,
    ok      boolean NOT NULL DEFAULT false,   -- did the code check pass (for triage, not policy)
    at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS signup_attempts_at_idx ON public.signup_attempts (at);
CREATE INDEX IF NOT EXISTS signup_attempts_email_at_idx ON public.signup_attempts (email, at);
CREATE INDEX IF NOT EXISTS signup_attempts_ip_at_idx ON public.signup_attempts (ip, at);

ALTER TABLE public.signup_attempts ENABLE ROW LEVEL SECURITY;


-- League ownership (P5/S2a) — the table that makes an account MEAN something.
--
-- Half of the one visibility predicate the whole app answers:
--     visible(league) = (league_id = DEMO_LEAGUE_ID)  OR  (owned by caller AND season = current)
-- The demo half is CONFIG (`settings.demo_league_id()`), deliberately not a row here: with exactly
-- one public league a table buys nothing, and a config value cannot drift from a loader-generated
-- artifact the way a seeded row can.
--
-- No `season` column, and that is on purpose. A redraft `league_id` already pins exactly one
-- (league, season) slice, so a season here would be a second copy of a fact `demo_manifest`
-- already holds — and the two would eventually disagree. The current-season term is applied at
-- read time by joining the catalog, not by trusting a denormalised column.
--
-- ON DELETE CASCADE for the same reason `app_users` has it: removing someone from the project
-- must not leave grants pointing at a user id that no longer exists.
--
-- What a row does NOT mean: that a human proved control of the address. S1b creates accounts with
-- `email_confirm: true` BEFORE the magic link is known to have sent, so a mailer failure leaves a
-- confirmed account behind (S1b audit, "Minor"). A grant is therefore an operator act about a
-- league, not evidence about a person. S4's connect flow writes the same row from the other
-- direction — a user claiming their own league — and that is where identity gets established.
CREATE TABLE IF NOT EXISTS public.user_leagues (
    user_id     uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    league_id   text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, league_id)
);

-- Same defense-in-depth caveat as above: the app connects as an owner role that BYPASSES RLS, so
-- this denies nothing to this API. Per-user isolation here is API-layer, by design (P5 settled).
ALTER TABLE public.user_leagues ENABLE ROW LEVEL SECURITY;

-- The viewer seat, as a USER × LEAGUE property (P5/S2b). Which roster is "you" was a property of
-- the *league* (`demo_manifest.viewer_roster_id`) — fine with one viewer, wrong the moment two
-- people share a league and each need their own highlight.
--
-- Nullable: a grant without a seat is normal (the operator may not know it, and S4's connect flow
-- learns it from Sleeper). Null falls back to `MY_USERNAME`, which is what keeps the demo's
-- behaviour exactly as it was.
--
-- THIS MUST BE AN EXPLICIT ALTER. `CREATE TABLE IF NOT EXISTS` above is a no-op on an existing
-- table, so a column added to that statement would silently never appear in any database that
-- already has the table — which is every database that matters. That is the S2a-audit F2 trap
-- ("a table that already existed in another shape keeps its old shape and nothing notices"), and
-- `init_auth_schema.verify()` now asserts this column is really present rather than trusting it.
ALTER TABLE public.user_leagues ADD COLUMN IF NOT EXISTS roster_id int;


-- Last-known-good NFL season (P5/S2a) — the persistence behind `settings.current_season()`.
--
-- The season comes from Sleeper's /v1/state/nfl rather than a constant, so it rolls over by itself
-- during the preseason. That makes a third-party outage part of the visibility path, and the
-- resolver must fail CLOSED: with no value at all, visibility collapses to the demo. It must never
-- degrade to "no season filter" — an outage that costs a user their own league for an hour is an
-- availability bug; one that makes every league visible is the silent isolation failure S2 exists
-- to prevent.
--
-- WHY A TABLE AND NOT AN IN-PROCESS CACHE: `min_machines_running = 0`, so an in-memory value dies
-- on every scale-to-zero — exactly the reasoning that put the rate limiter in Postgres above. A
-- cache that is empty every cold start is not a last-known-good.
--
-- Serving a STALE value during an outage is safe in one direction only, which is why it is
-- allowed: the season only rolls forward, so a stale value can at worst hide a league that just
-- became current. Narrowing, never widening.
--
-- One row, enforced by the primary key + CHECK rather than by convention.
CREATE TABLE IF NOT EXISTS public.nfl_state_cache (
    only_row    boolean PRIMARY KEY DEFAULT true CHECK (only_row),
    season      int NOT NULL,
    fetched_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.nfl_state_cache ENABLE ROW LEVEL SECURITY;
